// Code generated by MockGen. DO NOT EDIT.
// Source: handlers/handlerInterface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	echo "github.com/labstack/echo/v4"
)

// MockUserHandlersInterface is a mock of UserHandlersInterface interface.
type MockUserHandlersInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserHandlersInterfaceMockRecorder
}

// MockUserHandlersInterfaceMockRecorder is the mock recorder for MockUserHandlersInterface.
type MockUserHandlersInterfaceMockRecorder struct {
	mock *MockUserHandlersInterface
}

// NewMockUserHandlersInterface creates a new mock instance.
func NewMockUserHandlersInterface(ctrl *gomock.Controller) *MockUserHandlersInterface {
	mock := &MockUserHandlersInterface{ctrl: ctrl}
	mock.recorder = &MockUserHandlersInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserHandlersInterface) EXPECT() *MockUserHandlersInterfaceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserHandlersInterface) CreateUser(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserHandlersInterfaceMockRecorder) CreateUser(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserHandlersInterface)(nil).CreateUser), c)
}

// GetRate mocks base method.
func (m *MockUserHandlersInterface) GetRate(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRate", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetRate indicates an expected call of GetRate.
func (mr *MockUserHandlersInterfaceMockRecorder) GetRate(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRate", reflect.TypeOf((*MockUserHandlersInterface)(nil).GetRate), c)
}
